#!/usr/bin/env sh
. "$(dirname -- "$0")/_/husky.sh"

cd frontend
npm run lint || (echo "Linting failed. Please fix the issues before committing." && exit 1)
npm run lint:style || (echo "Style linting failed. Please fix the issues before committing." && exit 1)
npx lint-staged
